### ISSUE TITLE
Missing JSforce (f.k.a. Node-Salesforce) ?

### ISSUE THREAD

**Issue by liratanak** [mailtoharshit/awesome-salesforce#10]
Hi,

JSforce https://jsforce.github.io/

That is really cool lib in js for working with Salesforce's API
and I don't know what categories suitable for this, so create this issue.

Sincerely,
Liratanak

**Comment by mailtoharshit** [comment]
We will design a section for supporting libraries

**Comment by mailtoharshit** [comment]
This is added

**Comment by liratanak** [comment]
Look nice, thanks
